CREATE TABLE "SYSTEM"."DEPT" 
   (	"DEPTNO" NUMBER(*,0) NOT NULL ENABLE, 
	"DEPTNAME" VARCHAR2(14 BYTE), 
	"LOC" VARCHAR2(13 BYTE),
	"CITY" VARCHAR2(10 BYTE)
   )
  TABLESPACE "SYSTEM" ;

  CREATE UNIQUE INDEX "SYSTEM"."IDX1_EMP_DEPTNO" ON "SYSTEM"."DEPT" ("DEPTNO");
